app:
  title: '@name@'
  description: '@description@ -- DEFAULT --'
  version: '@version@'

server:
  port: 9292

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    time-to-live: 60
  jackson:
    parser:
      allow-numeric-leading-zeros: true

# change health check status code
management:
  endpoint:
    health:
      status:
        http-mapping:
          DOWN: 500
          UP: 200

# serasa configurations
serasa:
  url: "http://localhost:7171/bureau-serasa/capture"
